### PR TITLE
Docs: Start sphinx docs

### PR DESCRIPTION
**Pull request by TomAugspurger**
Some high-level notes:

1. I borrowed a couple utility functions from pandas / matplotlib for shared docstrings. These aren't as pleasant to use as simple docstrings, but we had a lot that could be shared between estimators, and I wanted to avoid that much duplication.
2. I'm using `nbsphinx` for the example notebooks. We started using it with pandas and haven't had any troubles. You might need `pandoc` on your path for this to work though.
3. I claimed `dask-glm` on https://readthedocs.org/projects/dask-glm/ @moody-marlin can I add you as a maintainer on there?

### CODE REVIEW

**Comment by mrocklin** [comment]
Looks like you can't assign to `__doc__` in Python 2.

**Comment by TomAugspurger** [comment]
Docs are up at http://dask-glm.readthedocs.io/en/latest/index.html

I'd rather not be the only maintainer there. @moody-marlin do you have a readthedocs.org account?

**Comment by moody-marlin** [comment]
@TomAugspurger sorry I haven't had a chance to thoroughly look at this; I just signed up for a readthedocs.org account; username: `moody-marlin`.  Totally cool joining you as a maintainer.

**Comment by TomAugspurger** [comment]
Thanks! I added you.

**Pull request merged**
