### PR TITLE
Use setuptools scm

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by postelrich** [comment]
@TomAugspurger I'm not familiar with setuptools_scm, how does it compare to versioneer?

**Comment by TomAugspurger** [comment]
Seems to be "blessed" by the PyPA https://github.com/pypa/setuptools_scm, so that's good enough reason for me :D

**Comment by postelrich** [comment]
Looks good to me.

**Comment by moody-marlin** [comment]
LGTM.

**Pull request merged**
