### PR TITLE
PKG: Use versioneer for version management

### PR DESCRIPTION
**Pull request by TomAugspurger**
Adds versioneer for auto-bumping the version when we tag a new release, and a few changes to the setup.py.

I think a release in the near-future would be worthwhile (PyPI and conda-forge). Once we get any blocking issues fixed, I can tag a 0.1.0 and do the release stuff.

### CODE REVIEW

**Comment by moody-marlin** [comment]
Re: a release, I added an [issue for discussion](https://github.com/dask/dask-glm/issues/54) on this.

**Comment by HolgerPeters** [comment]
@TomAugspurger any specific reason why not https://github.com/pypa/setuptools_scm instead of versioneer?

**Comment by HolgerPeters** [comment]
Setuptools scm does not require a  `versioneer.py` to be commited, and I have been successfully using it in almost all of my python projects (quite a few did use versioneer before).

**Comment by TomAugspurger** [comment]
No reason, other than familiarity with versioneer. You would recommend setuptools scm over it?

**Comment by HolgerPeters** [comment]
I do recommend setuptools_scm over versioneer.

**Comment by TomAugspurger** [comment]
Closing in favor of https://github.com/dask/dask-glm/pull/53

**Pull request closed without merging**
