### PR TITLE
Fix and clean dask-glm.utils.dot for cupy and sparse input

### PR DESCRIPTION
**Pull request by daxiongshu**
Edit: The original `dask-glm.utils.dot` doesn't work for `cupy` inputs. It doesn't work for `dot(sparse.array, dask.array)` either because `sparse.dot` is invoked and it isn't able to handle Dask arrays. Please find details below and in the threads.

In the original code of `dask_glm.utils.dot`, errors occur when `A` or `B` is a `cupy` array.
https://github.com/dask/dask-glm/blob/9eab0c277741f0a20b7f282a80519c7fb0fde1cd/dask_glm/utils.py#L107-L111

This is due to:
1. `package_of(x)` returns `None` if `x` is a `cupy` array.
2. Even if `package_of(x)` returns `cupy`, `x.__array_priority__` is 100  if `x` is a `cupy` array, which is greater than 10 of a `dask` array. So `cupy.dot(cupy.array, dask.array)` will be invoked and result in error.

This PR supports the follow calculation for `dask_glm.utils.dot` with `cupy` inputs:

1. `dot(cupy.array, cupy.array)`
2. `dot(cupy.array, dask.array with cupy chunks)`
3. `dot(dask.array with cupy chunks, cupy.array)`

`cupy` is not imported in this implementation. And a new test with `pytest.importorskip` is added to `dask_glm/tests/test_utils.py`.

### CODE REVIEW

**Comment by quasiben** [comment]
cc @hhuuggoo

**Comment by pentschev** [comment]
Why can't we just use `__array_function__` to do all of the dispatching?

```python
In [1]: import numpy as np, dask.array as da, cupy

In [2]: a = da.from_array(cupy.arange(100).reshape((10, 10)))

In [3]: b = cupy.arange(100).reshape((10, 10))

In [4]: np.dot(a, b)
Out[4]: dask.array<sum-aggregate, shape=(10, 10), dtype=int64, chunksize=(10, 10), chunktype=cupy.ndarray>

In [5]: np.dot(a, b).compute()
Out[5]:
array([[ 2850,  2895,  2940,  2985,  3030,  3075,  3120,  3165,  3210,
         3255],
       [ 7350,  7495,  7640,  7785,  7930,  8075,  8220,  8365,  8510,
         8655],
       [11850, 12095, 12340, 12585, 12830, 13075, 13320, 13565, 13810,
        14055],
       [16350, 16695, 17040, 17385, 17730, 18075, 18420, 18765, 19110,
        19455],
       [20850, 21295, 21740, 22185, 22630, 23075, 23520, 23965, 24410,
        24855],
       [25350, 25895, 26440, 26985, 27530, 28075, 28620, 29165, 29710,
        30255],
       [29850, 30495, 31140, 31785, 32430, 33075, 33720, 34365, 35010,
        35655],
       [34350, 35095, 35840, 36585, 37330, 38075, 38820, 39565, 40310,
        41055],
       [38850, 39695, 40540, 41385, 42230, 43075, 43920, 44765, 45610,
        46455],
       [43350, 44295, 45240, 46185, 47130, 48075, 49020, 49965, 50910,
        51855]])

In [6]: np.dot(b, a)
Out[6]: dask.array<sum-aggregate, shape=(10, 10), dtype=int64, chunksize=(10, 10), chunktype=cupy.ndarray>

In [7]: np.dot(b, a).compute()
Out[7]:
array([[ 2850,  2895,  2940,  2985,  3030,  3075,  3120,  3165,  3210,
         3255],
       [ 7350,  7495,  7640,  7785,  7930,  8075,  8220,  8365,  8510,
         8655],
       [11850, 12095, 12340, 12585, 12830, 13075, 13320, 13565, 13810,
        14055],
       [16350, 16695, 17040, 17385, 17730, 18075, 18420, 18765, 19110,
        19455],
       [20850, 21295, 21740, 22185, 22630, 23075, 23520, 23965, 24410,
        24855],
       [25350, 25895, 26440, 26985, 27530, 28075, 28620, 29165, 29710,
        30255],
       [29850, 30495, 31140, 31785, 32430, 33075, 33720, 34365, 35010,
        35655],
       [34350, 35095, 35840, 36585, 37330, 38075, 38820, 39565, 40310,
        41055],
       [38850, 39695, 40540, 41385, 42230, 43075, 43920, 44765, 45610,
        46455],
       [43350, 44295, 45240, 46185, 47130, 48075, 49020, 49965, 50910,
        51855]])
```

**Comment by daxiongshu** [comment]
@pentschev Thank you for the comment. I just tested and it works very well. I didn't see any performance slowdown. Do you think I should simply the PR as follows?
```
@dispatch(object, object)
def dot(A, B):
    if "cupy" in str(type(B)) or "cupy" in str(type(A)):
        return np.dot(A, B)
    else:
        x = max([A, B], key=lambda x: getattr(x, '__array_priority__', 0))
        module = package_of(x)
        return module.dot(A, B)
```

Actually I would rather prefer to replace all the 5 `def dot` with:
```
@dispatch(object, object)
def dot(A, B):
    return np.dot(A, B)
```

**Comment by pentschev** [comment]
I would remove `dot` entirely from dask-glm and replace it by `np.dot` wherever it's used. I don't see any reason to keep a function that's just wrapping NumPy.

**Comment by daxiongshu** [comment]
> I would remove `dot` entirely from dask-glm and replace it by `np.dot` wherever it's used. I don't see any reason to keep a function that's just wrapping NumPy.

I'm not sure if the `sparse` array also follows this numpy protocol. I'll test it.
https://github.com/pydata/sparse

**Comment by daxiongshu** [comment]
Below is one case that it doesn't work. But the original implementation of `dot` has the exact error:
```
import sparse
X = sparse.COO(np.zeros((4, 4)))
y = sparse.COO(np.arange(4))
dy = da.from_array(y, chunks=y.shape)
z = np.dot(X,dy)
z
```
Error message:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-0d6e3bd9d09d> in <module>
      3 y = sparse.COO(np.arange(4))
      4 dy = da.from_array(y, chunks=y.shape)
----> 5 z = np.dot(X,dy)
      6 z

<__array_function__ internals> in dot(*args, **kwargs)

~/anaconda3/envs/rapids0.15/lib/python3.7/site-packages/sparse/_sparse_array.py in __array_function__(self, func, types, args, kwargs)
    244             pass
    245         else:
--> 246             return sparse_func(*args, **kwargs)
    247 
    248         try:

~/anaconda3/envs/rapids0.15/lib/python3.7/site-packages/sparse/_common.py in dot(a, b)
    266     if b.ndim == 1:
    267         b_axis = -1
--> 268     return tensordot(a, b, axes=(a_axis, b_axis))
    269 
    270 

~/anaconda3/envs/rapids0.15/lib/python3.7/site-packages/sparse/_common.py in tensordot(a, b, axes, return_type)
    144     bt = b.transpose(newaxes_b).reshape(newshape_b)
    145     res = _dot(at, bt, return_type)
--> 146     return res.reshape(olda + oldb)
    147 
    148 

AttributeError: 'NoneType' object has no attribute 'reshape'
```

**Comment by pentschev** [comment]
As you noted, this is not related to `__array_function__` itself, this is because `sparse.dot` will end up getting called, because the sparse array is on the left and dispatching will occur left-to-right, and `sparse.dot` isn't able to handle Dask arrays. On the other hand, if you had the Dask array on the left side it would work:

```python
import numpy as np, dask.array as da, sparse
X = sparse.COO(np.zeros((4, 4)))
y = sparse.COO(np.arange(4))
dX = da.from_array(X, chunks=X.shape)
z = np.dot(dX, y)
```

The cleanest way to resolve within Dask is to ensure both arrays are Dask arrays, by wrapping them in `da.asarray` _before_ calling `np.dot`, e.g.:

```python
import numpy as np, dask.array as da, sparse
X = sparse.COO(np.zeros((4, 4)))
y = sparse.COO(np.arange(4))
dX = da.asarray(X, chunks=X.shape)
dy = da.asarray(y, chunks=y.shape)
z = np.dot(dX, y)
```

**Comment by daxiongshu** [comment]
>The cleanest way to resolve within Dask is to ensure both arrays are Dask arrays, by wrapping them in da.asarray before calling np.dot, e.g.:

@pentschev Great idea! I just test it and it passed all pytests. I will revise this PR accordingly. Thanks!

**Comment by daxiongshu** [comment]
I ended up doing the following because:
1. if both inputs are `cupy/numpy/sparse`, the result is expected to be `cupy/numpy/sparse` accordingly.
2. otherwise the output should be `dask array`.

```python
def _to_dask_array(x):
    if isinstance(x, da.Array):
        return x
    else:
        return da.from_array(x, chunks=x.shape)


@dispatch(object, object)
def dot(A, B):
    if isinstance(A, da.Array) or isinstance(B, da.Array):
        A = _to_dask_array(A)
        B = _to_dask_array(B)
    return np.dot(A, B)
```

**Comment by pentschev** [comment]
@daxiongshu you're still overcomplicating things, consider the `da.asarray` implementation in https://github.com/dask/dask/blob/ee0d205ce8bec289cefd5989b7af0d5cda67fe8b/dask/array/core.py#L3846-L3856. That is doing the same as you are in `_to_dask_array`, but it has a bonus of handling other cases such as `list`s and `xarray`. There's no need for you to reimplement that, please just use `da.asarray` instead.

**Comment by daxiongshu** [comment]
Thank you! It works great!

**Review by pentschev — APPROVED** [review]
Awesome, thanks a lot for these changes @daxiongshu ! Looks good to me.

**Comment by pentschev** [comment]
Could you also take a look at this @TomAugspurger ?

**Comment by TomAugspurger** [comment]
Thanks all!

**Pull request merged**
